# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

#logging.level.org.springframework.web: DEBUG

spring:
    application:
        name: HiOA Noark 5 Core (Dev mode)
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        show_sql: false
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.dialect: org.hibernate.dialect.H2Dialect
            hibernate.show_sql: false
            hibernate.hbm2ddl.auto: create-drop
            hibernate.hbm2ddl.import_files: classpath:/db/h2/dev/import.sql # Import some data into the developer database
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: target/lucene/indexes
            # Enable these to support elasticsearch, but wait until out of beta!
            #hibernate.search.default.indexmanager: elasticsearch
            #hibernate.search.default.elasticsearch.index_schema_management_strategy: CREATE # on applicatoin startup, create new index from db
            #hibernate.search.default.elasticsearch.host: https://localhost:9876 # Only required if not using localhost

    mail:
        host: localhost
    messages:
        basename: i18n/messages
        cache-seconds: 1
        encoding: UTF-8
    thymeleaf:
        cache: false
    output:
        ansi:
          enabled: ALWAYS
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
server:
    contextPath: /noark5v4
    port: 8092
management:
  context-path: /management

info.app.name: HiOA Noark 5 Core (Development)
info.build.version: ${project.version}

    #ssl:
    #    key-store: classpath:saml/nikitaKeystore.jks
    #    key-store-password: ********
    #    keyStoreType: JCEKS
    #    #PKCS12
    #    keyAlias: test-saml
# ===================================================================
# nikita-noark5-core specific properties
# ===================================================================

nikita-noark5-core:
    pagination:
          _maxPageSize: 10
    mail:
        from: nikita@example.com
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx.enabled: true
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: nikitaNoark5Core
        logs: # report metrics in the logs
            enabled: false
            reportFrequency: 60 # in seconds
    logging:
        level:
            ROOT: INFO
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queueSize: 512
    persistence:
         jpa.generateDdl: true
         # For Feide login
    saml:
         entityId: no:hioa:nikita:noark5

         idPUrl: http://nikita.hioa.no
         idPMetadata: https://idp-test.feide.no/simplesaml/saml2/idp/administration.php
    server:
         name: nikita.hioa.no
         port: 8092
         address: localhost
    details:
        conformity-levels:
            official: arkivstruktur, sakarkiv
            non-official: gui, import-api
    storage:
        location: /tmp/dokumenter
    checksumAlgorithm: SHA-256
